### ISSUE TITLE
Galaxy Tab 7" - Android 4.4 - v5 - JP - No data to save

### ISSUE THREAD

**Issue by namaless** [Caraxi/SIFAM#1]
Hello Caraxi, first really thanks for this great application.

Next I have tried the latest version v5 into bluestack and with jap version working fine, but into my galaxy tab not working.

When I try to save the data I give the toast message "No data to save". With EU version working fine.

I checked your source and I don't know what not working, btw I downloaded the v4 and with this working fine.

Tomorrow Ill try to install again the v5 and try to set the chmod for the data folder same at bluestack (777) and try again but I don't think this is a problem.

If I can help to you to found the problem no problem, ask to me what I can do ^_^

**Comment by Caraxi** [comment]
Hi, Sorry I never got around to replying to this. When I published to github I was on hiatus from SIF so I wasn't working on SIFAM. Are you able to tell me if the issue persists with the new versions?

**Comment by namaless** [comment]
Fixed with the latest version :)

**Comment by Caraxi** [comment]
Thats great to hear :)
