### ISSUE TITLE
Overlay not working Andoird Kitkat/Lollipop

### ISSUE THREAD

**Issue by namaless** [Caraxi/SIFAM#2]
Hey man,

I activate the overlay feature in the settings but with Kitkat (emulator) and Lollipo (tablet and smartphone) not see anything, I missed anything?

**Comment by Caraxi** [comment]
There is a bug in the current released version that causes the overlay to not display if only the "Display Loaded Account" overlay is enabled. 

Are you having this issue with both the "Display Close Button" and also the "Display Loaded Account" enabled at the same time?

**Comment by namaless** [comment]
I not activate the second option, give a sec :+1:

**Comment by namaless** [comment]
Ok with the closed button the account name I see :)

**Comment by namaless** [comment]
If you want I can testing or directly edit the source code and testing ;)

**Comment by Caraxi** [comment]
This issue was fixed in the most recent source code push. It will be updated to the SIFAM release on the next version :)

fb1f99e

**Comment by namaless** [comment]
Related to overlay I see one bug:

1. press button for switch window
2. when come back the overlay not see

---

Ok ill try the new sources for check the bug posted above :)

**Comment by Caraxi** [comment]
The overlay will only display until the next time SIFAM is opened and will not display again until SIF is launched from SIFAM

**Comment by namaless** [comment]
You don't think the possible to attack to game process? Sorry for noob question ;)

**Comment by Caraxi** [comment]
I'm don't know a way to attach to the game directly. If you find a way, let me know and I'll add it to SIFAM :)

**Comment by namaless** [comment]
Ok if I find a time in this week Ill try, btw really thanks for this great app and sources, u great :)
