### ISSUE TITLE
import com.google.zxing what you use?

### ISSUE THREAD

**Issue by namaless** [Caraxi/SIFAM#4]
i working on the source, but I never used this library, you can explain how I can get? Ty :)

**Comment by Caraxi** [comment]
Are you using android studio?

**Comment by namaless** [comment]
Yes I search on modules, I found the integration but if you know what module is much faster :dancer:

**Comment by namaless** [comment]
import com.google.zxing.integration.android.IntentIntegrator;
import com.google.zxing.integration.android.IntentResult;

this is ok, i search the other

**Comment by Caraxi** [comment]
I just add them to gradle's build.gradle. For example, here's how mine look

https://gist.github.com/Caraxi/e878348c3435e7953fa0

**Comment by namaless** [comment]
Nice, thanks :)
